


secretStore:
  name: vault-backend
  kind: ClusterSecretStore

# Secret provisioned for the AWS Controller for Kubernetes - S3 
minioRootCreds:
  key: secret/data/global/minio_root


# Begin global parameters

operator:
  operator:
    env:
    - name: "MINIO_OPERATOR_RUNTIME"
      value: "OpenShift"
    - name: MINIO_CONSOLE_TLS_ENABLE
      value: "off"
      # may need to set
      # - name: CLUSTER_DOMAIN
      #   value: "cluster.domain"
  console:
    enabled: false # Strip right now.
tenant:
  secrets:
    name: minio-tenant-secret
    existingSecret:
      name: enabled
  tenant:
    name: my-minio-tenant
    configuration:
      name: minio-tenant-secret
      existingSecret: true
    pools:
    - servers: 1
      name: mypool
      size: 20Gi
      volumesPerServer: 3
    # metrics:
    # features:
    buckets:
    - name: my-minio-bucket
      # objectLock: false        # optional
      # region: us-east-1
    # users:
    # -

