


secretStore:
  name: vault-backend
  kind: ClusterSecretStore

# Secret provisioned for the AWS Controller for Kubernetes - S3 
minioRootCreds:
  key: secret/data/global/minio_root


# Begin global parameters





operator:
  operator:
    env:
    - name: "MINIO_OPERATOR_RUNTIME"
      value: "OpenShift"
    securityContext:
      runAsUser: 1000770000
      runAsGroup: 1000770000
      fsGroup: 1000770000
    containerSecurityContext:
      runAsUser: 1000770000
      runAsGroup: 1000770000
  console:
    securityContext:
      runAsUser: 1000770000
    containerSecurityContext:
      runAsUser: 1000770000

tenant:
  tenant:
    name: my-minio-tenant
    pools:
    - servers: 1
      name: mypool
      size: 20Gi
      volumesPerServer: 3
    # metrics:
    # features:
    buckets:
    - name: my-minio-bucket
      # objectLock: false        # optional
      # region: us-east-1
    # users:
    # -
