
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints 
metadata:
  name: milvus-operator-scc
  namespace: 
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny 
fsGroup:
  type: RunAsAny
users:
  - system:serviceaccount:milvus-operator:milvus