kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: minio-scc
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 1000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 1000
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- secret
users:
- system:serviceaccount:minio-operator:minio-operator
- system:serviceaccount:minio-operator:console-sa