---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odh-cluster-role
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: ["datasciencecluster.opendatahub.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["image.openshift.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["kubeflow.org"]
    resources: ["notebooks"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets", "services"]
    verbs: ["*"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
