apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-test
  namespace: milvus
  labels:
    app: milvus
spec:
  config:
    minio:
      # your bucket name
      bucketName: milvus
      # Optional, config the prefix of the bucket milvus will use
      rootPath: test-v1
      useSSL: true
  dependencies:
    storage:
      # enable external object storage
      external: true
      type: S3 # MinIO | S3
      # the endpoint of AWS S3
      endpoint: s3.openshift-storage.svc:443
      # the secret storing the access key and secret key
      secretRef: "milvus-obc-clean"
    etcd:
      inCluster:
        values:
          replicaCount: 3
          resources:
            limits:
              cpu: 1
              memory: 4Gi
        deletionPolicy: Delete
        pvcDeletion: true