apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: {{ .Values.dsp.name }}
  name: local-queue-test
  annotations:
    kueue.x-k8s.io/default-queue: 'true'
    argocd.argoproj.io/sync-wave: "10"
spec:
  clusterQueue: cluster-queue-b