kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.dsp.name }}
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/description: 'RHOAI llm demo project'
    openshift.io/display-name: {{ .Values.dsp.name }}
spec: {}