---
name: Helm lint

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on: [push, pull_request]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Unit Test Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.2'
        id: install

      - name: Run make helmlint
        run: |
          make helmlint

      # Disable kubeconform for the time being
      # - name: Run make helm kubeconform
      #   run: |
      #     curl -L -O https://github.com/yannh/kubeconform/releases/download/v0.4.13/kubeconform-linux-amd64.tar.gz
      #     tar xf kubeconform-linux-amd64.tar.gz
      #     sudo mv -v kubeconform /usr/local/bin
      #     make kubeconform
