apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: default-bucket
  namespace: openshift-storage
  labels:
    app: noobaa
spec:
  placementPolicy:
    tiers:
      - backingStores:
          - local-backingstore
        placement: Spread